interface=nm-bridge
port=53
server=223.5.5.5
server=8.8.8.8
enable-ra
resolv-file=/etc/dnsmasq-resolv.conf
dhcp-range=192.168.100.2,192.168.100.254,12h
dhcp-range=::,constructor:nm-bridge,ra-stateless,12h
dhcp-option=option:router,192.168.100.1
dhcp-option=option:dns-server,192.168.100.1
dhcp-option=option:ntp-server,192.168.100.1
dhcp-option=option:netmask,255.255.255.0
dhcp-option=option6:dns-server,[fe80::d477:9db8:183b:2930]
listen-address=192.168.100.1,127.0.0.1

