name: Build kernel deb packages
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Prepare
        run: |
          apt -y update
          apt -y install git lsb-release gcc-aarch64-linux-gnu bison flex libssl-dev libelf-dev debhelper bc rsync kmod cpio

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare repository
        run: git config --global --add safe.directory "$(pwd)"

      - name: Build
        run: |
          export CROSS_COMPILE=aarch64-linux-gnu-
          export ARCH=arm64
          make sp970_defconfig
          make deb-pkg -j"$(($(grep -c processor < /proc/cpuinfo)*2))"

      - name: Prepare artifacts
        run: |
          mkdir artifacts && mv ../linux-image-*.deb ../linux-headers-*.deb artifacts/
          cp arch/arm64/boot/dts/qcom/msm8916-cj-sp970.dtb artifacts/
          cp arch/arm64/boot/Image.gz artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel
          path: artifacts/*

  bootimg:
    name: Make boot images
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt -y update
          sudo apt -y install binfmt-support qemu-user-static mkbootimg
          mkdir artifacts

      - name: Checkout
        uses: actions/checkout@v4

      - name: Download kernel
        uses: actions/download-artifact@v4
        with:
          name: kernel
          path: artifacts

      - name: Build
        run: |
          cd .github/scripts
          chmod +x build_boot_img.sh
          sudo ./build_boot_img.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel and boot images
          path: artifacts/*